name: ws_debug_servers
description: "Dual WebSocket servers for the debug prototype."
publish_to: 'none'

environment:
  sdk: ^3.10.4

dependencies:
  shelf: ^1.4.1
  shelf_web_socket: ^1.0.4
  web_socket_channel: ^2.4.0
